repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-symlinks
      # - id: check-json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check CKV_AWS_338


  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.1
    hooks:
      - id: sqlfluff-fix
        name: Fix SQL files
        types: [sql]
